### ISSUE TITLE
Linux Builds on Travis CI

### ISSUE THREAD

**Issue by zethon** [zethon/Owl#58]
Owl currently builds on Ubuntu 18.04 but Travis CI only has support for Ubuntu 14.04 (and 12.04). This causes problems with the C++11 ABI issue. 

There are notes in the `.travis.yml` file to describe the issue. It would be nice to get CI working with Linux, perhaps once I have time to rebuild Hunspell making sure that it uses the `libstdc++` library (and **not** `libstdc++11`) so that it will properly link, or when there is time to learn how to use Docker to do the builds on Travis.

Per the notes in the `.travis.yml` file:

```
# NOTE: Where we left off with Linux -- the -D_GLIBCXX_USE_CXX11_ABI=[0|1] does nothing
# on the older version of Ubuntu (14.04) that Travis CI uses. Hence when I tried to link 
# everything against the C++11 system libraries, I still got linker errors about 
# "undefined reference to `std::__cxx11::basic_string...". When I tried to build against the
# old libs, I get the same linker errors. These all seem related to hunspell. One possible
# solution would be to re-build Hunspell and link against the old system libraries, but I'm
# (1) not entirely that will work on 18.04, which is the Ubuntu version I'm using and (2)
# I seem to remember something about static libraries not linking until they're linked with
# an executable but maybe that depends on the implementation? I had to explicitly link the 
# Conan libraries with the Owl libraries in order to avoid linking errors. ANOTHER possible
# solution would be to use Docker, but that's an entire learning curve and pain in the ass 
# that I don't want to deal with right now.
# 
# I'm going to put this to rest for a little bit so I can move on and work on other areas I want 
# to work on. Hopefully Travis will support Ubuntu 16.04 (or possibly 18.04) soon and this will
# "just work". In the meantime I leave the Linux build info here for future reference.
```

**Comment by zethon** [comment]
Travis-CI added support for Ubuntu 18.04 (bionic). Support for a bionic build was added with https://github.com/zethon/Owl/pull/85
